In [1]:
import numpy as np

In [3]:
weight_vector = np.array([[1], [1], [1]])
x_vector = np.array([[3], [4], [5]])

In [5]:
weight_vector

array([[1],
       [1],
       [1]])

In [6]:
x_vector

array([[3],
       [4],
       [5]])

In [4]:
weight_vector.T.dot(x_vector)

array([[12]])

In [7]:
import pandas as pd

data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"
df_data = pd.read_csv(data_url, sep="\s+", header = None) # 블랭크가 여러개 있을 경우 sep으로 봐라 

In [8]:
df_data.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [9]:
df_data['weight_0']= 1
df_data = df_data.drop("MEDV", axis=1) # y
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98         1  
1     17.8  396.90   9.14         1  
2     17.8  392.83   4.03         1  
3     18.7  394.63   2.94         1  
4     18.7  396.90   5.33         1

In [11]:
df_data.values[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00, 1.000e+00])

In [13]:
df_data.shape

(506, 14)

In [18]:
# dataframe -> numpy
# XW = Y
df_matrix = df_data.values
weight_vector = np.random.random_sample((14, 1))

In [22]:
df_matrix.dot(weight_vector)

array([[421.97436764],
       [403.4479536 ],
       [382.5162938 ],
       [358.94887455],
       [369.27767687],
       [371.27714134],
       [434.20333319],
       [465.60760185],
       [471.26287909],
       [449.87627507],
       [462.85433926],
       [449.72605935],
       [409.80971244],
       [419.34860754],
       [431.94990944],
       [414.14716444],
       [384.62862732],
       [436.15749586],
       [343.78175774],
       [425.05377777],
       [449.6468868 ],
       [445.06691769],
       [453.2215626 ],
       [459.87116242],
       [452.04339185],
       [397.68507188],
       [438.55336463],
       [402.74439637],
       [446.77063799],
       [436.11954068],
       [438.89855173],
       [445.87814663],
       [366.24561354],
       [435.84912969],
       [382.10874999],
       [412.11518791],
       [397.39534426],
       [388.1356946 ],
       [377.5503305 ],
       [398.68885308],
       [391.98324504],
       [324.42248964],
       [326.97235094],
       [333