# Numerical python, numpy

## 1. ndarray creation

In [1]:
import numpy as np

### 타입을 명시함으로써 dynamic typing is not supported
- 스트링을 입력해도 자동 변환 해준다
- np.int, np.float, np.str ...
- cf) https:/jakevdp.github.io/blog/2014/05/09/why-python-is-slow 

In [2]:
test_array = np.array([1,4,5,8], dtype=np.float32) 
print(test_array)

[1. 4. 5. 8.]


In [3]:
type(test_array[3]) # 8 bytes

numpy.float32

In [4]:
test_array.dtype

dtype('float32')

In [5]:
test_array.shape # 1차원에 4개의 element가 있는 벡터

(4,)

In [6]:
matrix = [[1,2,5,6],[1,2,5,8],[1,2,3,4]]
test_matrix = np.array(matrix, dtype=int)
test_matrix.shape

(3, 4)

In [7]:
test_matrix.ndim # num of dimension

2

In [8]:
test_matrix.size

12

### c의 데이터 타입과 ndarray의 타입은 호환 된다고 함
- https://www.slideshare.net/enthought/numpy-talk-at-siam
- 큰 데이터를 다루는 경우 주의

In [9]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.float32).nbytes # ndarray object의 메모리 크기 반환

24

In [10]:
np.array([[1,2,3],[4.5,"5","6"]], dtype=np.int8).nbytes

6

In [11]:
np.array([[1,2,3,],[4.5,"5","6"]], dtype=np.float64).nbytes

48

## 2. Shape Handling
- Array의 size만 같다면 다차원으로 변형(reshape) 가능 (크기 안맞을 경우 ValueError)
- -1을 전달할 경우 size를 기반으로 개수를 선정한다
- flatten 을 통해 다차원 array를 1차원 array로 변환 가능

In [12]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [13]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [14]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [15]:
# -1: size를 기반으로 row 개수 선정
np.array(test_matrix).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [16]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [17]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

In [18]:
np.array(test_matrix).reshape(2,-1)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [19]:
test_matrix = [[[[1,2,3,4], [1,2,5,6]], [[1,2,3,8], [1,2,5,9]]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 6, 1, 2, 3, 8, 1, 2, 5, 9])

## 3. Indexing
- 이차원 배열에서 [0,0] 과 같은 표기법 제공

In [20]:
a = np.array([[1,2,3],[4.5,5,6]], int)
print(a)
print(a[0,0])
print(a[0][0])

[[1 2 3]
 [4 5 6]]
1
1


In [21]:
a[0,0] = 12
a

array([[12,  2,  3],
       [ 4,  5,  6]])

## 4. Slicing
- https://www.slideshare.net/pydata/introduction-to-numpy
- arr[:, ::2] 은 시작:끝:스텝 이기 때문에 0열,2열,4열을 잘라온다

In [22]:
a = np.array([[1,2,3,4,5,], [6,7,8,9,10]], int)

In [23]:
a[:,2:] # 2열부터 끝까지

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [24]:
a[1,1:3] # 1 Row 의 1열~2열

array([7, 8])

In [25]:
a[1:3] # 1 Row ~ 2Row

array([[ 6,  7,  8,  9, 10]])

In [26]:
b = np.arange(100).reshape(10,10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
b[:, -1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

## 5. Creation function
- np.arange
- ones, zeros, empty (mem 초기화 x)
- something_like (ones_like)

In [28]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
np.arange(0, 5, 0.5) # 시작 끝 스텝(float가능)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [30]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
np.arange(50).reshape(5,5,2).shape

(5, 5, 2)

In [32]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [33]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.empty(shape=(100,), dtype=np.int8)

array([-40, -37, -56, -67,  -4, 126,   0,   0, -40, -37, -56, -67,  -4,
       126,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0, 112,   0,   0,   0], dtype=int8)

In [35]:
np.array(test_matrix).shape

(1, 2, 2, 4)

In [36]:
np.ones_like(test_matrix).shape

(1, 2, 2, 4)

## 6. linear algebra
- identity, eye, diag
- ★ random sampling ; 데이터 분포에 따른 sampling으로 array 생성

In [37]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [38]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.eye(N=3, M=5, dtype=np.int8) # identity 와 다른 점은 시작점 지정 가능

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.eye(3,5,k=2) # k는 시작점!

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [43]:
np.diag(matrix, k=1) # k는 시작점!

array([1, 5])

In [44]:
np.random.uniform(0,1,10).reshape(2,5) # 균등 분포 (0부터 1사이)

array([[0.18610672, 0.6766981 , 0.98607626, 0.9144193 , 0.28932635],
       [0.98519136, 0.60749447, 0.69750595, 0.74519831, 0.16035398]])

In [45]:
np.random.normal(0,1,10).reshape(2,5) # 정규 분포 (평균 0, std 1)

array([[ 1.17100242,  1.57773531,  0.32488438,  0.29082685,  0.66183537],
       [ 0.1176202 , -1.97448514, -0.13912301,  0.07598837,  0.88713942]])

## 7. Operation functions
- numpy의 계산 함수
- ★ axis 개념 이해 ; 파이썬에선 shape의 하나하나 크기를 axis라고 부름
- 1차원 벡터 (7,) 에서 axis=0은 7 부분임
- 2차원 벡터 메트릭스 (5,3)에서 axis=0은 5부분임
- 즉, shape에서 제일 앞에 있는게 axis=0
- mean & std
- concatenate ; vstack, hstack, concatenate

In [46]:
np.arange(1,11).sum(dtype=np.float)

55.0

In [47]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
test_array.sum()

78

#### Axis 이해

In [49]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [50]:
third_order_tensor = np.array([np.arange(1, 13).reshape(3,4) for i in range(3)])

In [51]:
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [52]:
third_order_tensor.shape

(3, 3, 4)

In [53]:
third_order_tensor.sum(axis=0) # 모양을 생각하기!

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [54]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [55]:
third_order_tensor.mean()

6.5

In [56]:
third_order_tensor.mean(axis=0)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [57]:
third_order_tensor.std()

3.452052529534663

In [58]:
np.exp(np.arange(10))

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [59]:
np.sqrt(np.arange(1,11).reshape(2,5))

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

#### Concatenation

In [60]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [61]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [62]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [63]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## 8. Array operaion (btw array)
- element-wise operation
- dot product
- broadcasting ; 같은 shape 끼리는 element wise op 이지만, 

In [64]:
test_a =  np.array([[1,2,3],[4,5,6]], float)

In [65]:
test_a + test_a 

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [66]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [67]:
test_a = np.arange(1,7).reshape(2,3)
print(test_a)
test_b = np.arange(7,13).reshape(3,2)
print(test_b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


#### Dot product

In [68]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [69]:
test_a.transpose() , test_a.T

(array([[1, 4],
        [2, 5],
        [3, 6]]), array([[1, 4],
        [2, 5],
        [3, 6]]))

In [70]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

##### Broadcasting

In [71]:
test_a + 3 # broadcasting

array([[4, 5, 6],
       [7, 8, 9]])

In [72]:
test_a * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [73]:
test_a ** 2 # 제곱

array([[ 1,  4,  9],
       [16, 25, 36]])

In [74]:
test_a // 0.2 # 몫

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

#### Vector - matrix 연산도 가능

In [75]:
test_c = np.array([np.arange(0,40,10) for i in range(3)]).T

test_c

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [76]:
test_c + np.array([0,1,2], int)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [77]:
test_d = np.array([np.arange(0,40,10)], int).T
test_d

array([[ 0],
       [10],
       [20],
       [30]])

In [78]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,50,10).reshape(4,1)

In [79]:
test_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
test_vector

array([[10],
       [20],
       [30],
       [40]])

In [81]:
test_matrix + test_vector

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39],
       [50, 51, 52]])

In [82]:
# 이런식으로도 가능하지만 직관적이지 못해 추천 xx
test_d + np.array([0,1,2],int)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

#### Performance 

In [83]:
def scalar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

#iteration_max = 100000000
iteration_max = 10000

vector = list(range(iteration_max))
scalar = 2

In [84]:
%timeit scalar_vector_product(scalar, vector) # for loop

858 µs ± 50.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [85]:
%timeit [scalar * value for value in range(iteration_max)] # list comprehension

601 µs ± 3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [86]:
%timeit np.arange(iteration_max) * scalar # numpy

14.4 µs ± 157 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 9. Comparison

In [87]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### all & any

In [88]:
np.any(a>5), np.any(a<0)

(True, False)

In [89]:
np.all(a>5), np.all(a<10)

(False, True)

In [90]:
a < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

#### Comparison
- 배열 크기 동일 할 때, element-wise 비교 결과
- logical_and / not / or
- ★ np.where(condition, TRUE, FALSE)
- isnan, isfinite
- ★ argmax, argmin

In [91]:
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b

array([False,  True, False])

In [92]:
test_a == test_b

array([False, False, False])

In [93]:
(test_a > test_b).any() # 하나라도 true이면

True

In [94]:
a = np.array([1,3,0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [95]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [96]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

In [97]:
a

array([1., 3., 0.])

In [98]:
np.where(a> 0, 3, 2)

array([3, 3, 2])

In [99]:
a = np.arange(10) + np.arange(10)
np.where(a > 5) # true 인 값의 인덱스

(array([3, 4, 5, 6, 7, 8, 9]),)

In [100]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [101]:
np.isfinite(a)

array([ True, False, False])

In [102]:
a = np.array([1,2,3,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(6, 0)

In [103]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [104]:
np.argmax(a, axis=1)

array([3, 3, 3])

In [105]:
np.argmin(a, axis=0)

array([0, 0, 0, 0])

## 10. Boolean & Fancy index
- numpy 배열로부터 특정 조건에 따라 값을 추출할 수 있다.
- 불린 배열을 인덱스로 전달하면 true인 element만 추출할 수 있다.

#### Boolean index

In [106]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [107]:
test_array[test_array > 3] # true인 element 만 추출

array([4., 8., 9., 7.])

In [108]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [109]:
A = np.array([np.arange(0,10) for i in range(10)])
A

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [110]:
B = A < 5
B

array([[ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False]])

In [111]:
B.astype(np.int)

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

#### Fancy index
- array를 index value로 사용해서 값을 추출!
- matrix 형태도 가능


In [112]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) # 반드시 int
a[b] # bracket index, b 배열 값을 index로 a의 값을 추출

array([2., 2., 4., 8., 6., 4.])

In [113]:
a.take(b) # 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [114]:
a = np.array([[1,4],[9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [115]:
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])

## 11. Data I/O

#### loadtxt & savetxt

In [117]:
a = np.loadtxt("./populations.txt") # default float (shift tab)
a[:10]

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.]])

In [118]:
a_int = a.astype(int)
a_int[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [119]:
np.savetxt('int_data.csv', a_int, delimiter=",") 

In [121]:
np.savetxt('int_data2.csv', a_int, fmt='%d', delimiter='\t')

#### object - npy

In [127]:
np.save("npy_test.npy", arr=a_int)

In [128]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [129]:
npy_array

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500],
       [ 1903, 77400, 35200, 38200],
       [ 1904, 36300, 59400, 40600],
       [ 1905, 20600, 41700, 39800],
       [ 1906, 18100, 19000, 38600],
       [ 1907, 21400, 13000, 42300],
       [ 1908, 22000,  8300, 44500],
       [ 1909, 25400,  9100, 42100],
       [ 1910, 27100,  7400, 46000],
       [ 1911, 40300,  8000, 46800],
       [ 1912, 57000, 12300, 43800],
       [ 1913, 76600, 19500, 40900],
       [ 1914, 52300, 45700, 39400],
       [ 1915, 19500, 51100, 39000],
       [ 1916, 11200, 29700, 36700],
       [ 1917,  7600, 15800, 41800],
       [ 1918, 14600,  9700, 43300],
       [ 1919, 16200, 10100, 41300],
       [ 1920, 24700,  8600, 47300]])